//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureBikeShop.Sites {
    
    
    public partial class WynikiWyszukiwania {
        
        /// <summary>
        /// WynikiWyszukiwaniaGridView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView WynikiWyszukiwaniaGridView;
        
        /// <summary>
        /// Szukaj control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AdventureBikeShop.Kontrolki.Szukaj Szukaj;
    }
}
